# Generated by Django 5.2.7 on 2025-10-15 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('Assignment', 'Assignment'), ('Quiz', 'Quiz'), ('Test', 'Test'), ('Project', 'Project'), ('Homework', 'Homework'), ('Midterm', 'Midterm'), ('Final', 'Final'), ('Participation', 'Participation')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_recorded', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='admin_api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='admin_api.subject')),
            ],
            options={
                'ordering': ['-date_recorded', '-created_at'],
            },
        ),
    ]
