# Generated by Django 5.2.7 on 2025-10-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_grade'),
    ]

    operations = [
    ]
