# Generated by Django 5.2.7 on 2025-10-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_class_date_class_day_of_week_class_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('library', 'Library'), ('auditorium', 'Auditorium'), ('gymnasium', 'Gymnasium'), ('office', 'Office'), ('other', 'Other')], default='classroom', max_length=20)),
                ('capacity', models.IntegerField(default=30)),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('building', models.CharField(blank=True, max_length=50)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_computer', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
    ]
