# Generated by Django 5.2.7 on 2025-10-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='calendar_type',
            field=models.CharField(choices=[('AD', 'AD (Gregorian)'), ('BS', 'BS (Bikram Sambat)')], default='AD', max_length=2),
        ),
    ]
