# Generated by Django 5.2.7 on 2025-10-30 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0014_timeslot_announcement_assignment_exam_feestructure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('Facebook', 'Facebook'), ('Website', 'Website'), ('Google', 'Google'), ('Referral', 'Referral'), ('Walk-in', 'Walk-in'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('query_date', models.DateField(default=django.utils.timezone.now)),
                ('last_follow_up_date', models.DateField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=50, null=True)),
                ('number_of_child', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Follow Up', 'Follow Up'), ('Contacted', 'Contacted'), ('Converted', 'Converted'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Query',
                'verbose_name_plural': 'Admission Queries',
                'ordering': ['-query_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_by', models.CharField(max_length=200)),
                ('complaint_type', models.CharField(choices=[('Academic', 'Academic'), ('Administrative', 'Administrative'), ('Facilities', 'Facilities'), ('Transport', 'Transport'), ('Staff', 'Staff'), ('Other', 'Other')], max_length=50)),
                ('source', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('In Person', 'In Person'), ('Online Portal', 'Online Portal')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('call_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('call_type', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phone Call Log',
                'verbose_name_plural': 'Phone Call Logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostalDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_title', models.CharField(max_length=200)),
                ('reference_no', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('from_title', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Postal Dispatch',
                'verbose_name_plural': 'Postal Dispatches',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostalReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_title', models.CharField(max_length=200)),
                ('reference_no', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('to_title', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Postal Receive',
                'verbose_name_plural': 'Postal Receives',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('id_card', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_person', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor Record',
                'verbose_name_plural': 'Visitor Book',
                'ordering': ['-date', '-in_time'],
            },
        ),
    ]
