# Generated by Django 5.2.7 on 2025-10-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0015_admissionquery_complaint_phonecalllog_postaldispatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_practical',
            field=models.BooleanField(default=False),
        ),
    ]
