# Generated by Django 5.2.7 on 2025-10-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0016_subject_is_practical'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], default='theory', max_length=10),
        ),
    ]
