# Generated by Django 5.2.7 on 2025-10-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0017_subject_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, help_text='e.g., A, B, C', max_length=10),
        ),
    ]
