# Generated by Django 5.2.7 on 2025-11-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0020_studentcategory_studentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSendingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
