# Generated by Django 5.2.7 on 2025-11-01 06:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0029_student_parent_user_paymenttransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('auto_graded_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('tab_switches', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='admin_api.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='admin_api.student')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='MeritList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3'), ('annual', 'Annual')], max_length=10)),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_lists', to='admin_api.academicyear')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_date'],
                'unique_together': {('academic_year', 'class_name', 'term')},
            },
        ),
        migrations.CreateModel(
            name='ProgressCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3'), ('annual', 'Annual')], max_length=10)),
                ('class_name', models.CharField(max_length=50)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('grade', models.CharField(max_length=5)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('total_days', models.IntegerField(default=0)),
                ('days_present', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('class_teacher_remarks', models.TextField(blank=True)),
                ('principal_remarks', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('parent_signature', models.BooleanField(default=False)),
                ('parent_signature_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_cards', to='admin_api.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_cards', to='admin_api.student')),
            ],
            options={
                'ordering': ['-academic_year', 'term', 'rank'],
                'unique_together': {('student', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_class', models.CharField(max_length=50)),
                ('to_class', models.CharField(max_length=50)),
                ('promotion_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='admin_api.academicyear')),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='admin_api.student')),
                ('to_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='admin_api.academicyear')),
            ],
            options={
                'ordering': ['-promotion_date'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('applying_for_class', models.CharField(max_length=50)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_grade', models.CharField(blank=True, max_length=50)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_occupation', models.CharField(blank=True, max_length=100)),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('admitted', 'Admitted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('birth_certificate', models.CharField(blank=True, max_length=500)),
                ('previous_report_card', models.CharField(blank=True, max_length=500)),
                ('transfer_certificate', models.CharField(blank=True, max_length=500)),
                ('medical_records', models.CharField(blank=True, max_length=500)),
                ('photo', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admin_api.academicyear')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application', to='admin_api.student')),
            ],
            options={
                'ordering': ['-applied_date'],
                'indexes': [models.Index(fields=['status', 'applied_date'], name='admin_api_a_status_3102ef_idx'), models.Index(fields=['application_number'], name='admin_api_a_applica_398714_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeritListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('merit_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='admin_api.meritlist')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_entries', to='admin_api.student')),
                ('progress_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_entries', to='admin_api.progresscard')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('merit_list', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='ProgressCardSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=5)),
                ('teacher_remarks', models.TextField(blank=True)),
                ('progress_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='admin_api.progresscard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.subject')),
            ],
            options={
                'unique_together': {('progress_card', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('selected_option', models.CharField(blank=True, max_length=10)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='admin_api.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='admin_api.examsession')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
    ]
