# Generated by Django 5.2.7 on 2025-11-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0032_examtype_gradescale_holiday_payrollcomponent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="designation",
            name="designation_type",
            field=models.CharField(
                choices=[
                    ("teaching", "Teaching Staff"),
                    ("administrative", "Administrative Staff"),
                    ("support", "Support Staff"),
                ],
                default="teaching",
                help_text="Category of designation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="designation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="designation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
